name: Skibidi_tualet

on:
  schedule:
    - cron: ' * * */2 *' # Сбор каждые 6 часов
  workflow_dispatch:      # Кнопка ручного запуска в интерфейсе GitHub

permissions:
  contents: write

jobs:
  gather-data:
    runs-on: ubuntu-latest # Используем бесплатный быстрый Linux от GitHub
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Fetcher Dependencies
        run: |
          pip install aiohttp

      - name: Run Original Fetcher with SNI Filter
        run: |
          python fetcher.py

      - name: Push Clean Chunks to Repository
        run: |
          git config --local user.email "fetcher_bot@github.com"
          git config --local user.name "VLESS Chunker Bot"
          git add raw_chunks/chunk_*.txt core/*.json logs/*.txt
          
          # Проверяем, изменились ли чанки, чтобы не делать пустые коммиты
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update clean chunks [skip ci]" && git push)
