name: Skibidi_Tualet_VPN

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        shell: cmd
        run: "C:\\Users\\Skibidi_tualet\\AppData\\Local\\Python\\pythoncore-3.14-64\\python.exe main.py"

        continue-on-error: true

